// This file is generated by running the atlas_builder.
package shooter

/*
Note: This file assumes the existence of a type Rect that defines a rectangle in the same package, it can defined as:

	Rect :: rl.Rectangle

or if you don't use raylib:

	Rect :: struct {
		x, y, width, height: f32,
	}

or if you want to use integers (or any other numeric type):

	Rect :: struct {
		x, y, width, height: int,
	}

Just make sure you have something along those lines the same package as this file.
*/

TEXTURE_ATLAS_FILENAME :: "data/atlas.png"
ATLAS_FONT_SIZE :: 32
LETTERS_IN_FONT :: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890?!&.,_:[]-+"

// A generated square in the atlas you can use with rl.SetShapesTexture to make
// raylib shapes such as rl.DrawRectangleRec() use the atlas.
SHAPES_TEXTURE_RECT :: Rect {0, 200, 10, 10}

Texture_Name :: enum {
	None,
	Player0,
	Player1,
}

Atlas_Texture :: struct {
	rect: Rect,
	// These offsets tell you how much space there is between the rect and the edge of the original document.
	// The atlas is tightly packed, so empty pixels are removed. This can be especially apparent in animations where
	// frames can have different offsets due to different amount of empty pixels around the frames.
	// In many cases you need to add {offset_left, offset_top} to your position. But if you are
	// flipping a texture, then you might need offset_bottom or offset_right.
	offset_top: f32,
	offset_right: f32,
	offset_bottom: f32,
	offset_left: f32,
	document_size: [2]f32,
	duration: f32,
}

atlas_textures: [Texture_Name]Atlas_Texture = {
	.None = {},
	.Player0 = { rect = {29, 0, 24, 24}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {24, 24}, duration = 0.100},
	.Player1 = { rect = {54, 0, 24, 24}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {24, 24}, duration = 0.100},
}

Animation_Name :: enum {
	None,
	Player_Walk,
}

Tag_Loop_Dir :: enum {
	Forward,
	Reverse,
	Ping_Pong,
	Ping_Pong_Reverse,
}

// Any aseprite file with frames will create new animations. Also, any tags
// within the aseprite file will make that that into a separate animation.
Atlas_Animation :: struct {
	first_frame: Texture_Name,
	last_frame: Texture_Name,
	document_size: [2]f32,
	loop_direction: Tag_Loop_Dir,
	repeat: u16,
}

atlas_animations := [Animation_Name]Atlas_Animation {
	.None = {},
	.Player_Walk = { first_frame = .Player0, last_frame = .Player1, loop_direction = .Forward, repeat = 0, document_size = {0, 0} },
}

// The rect inside the atlas where each tile has ended up.
// Index using tileset_ping[x][y].
tileset_ping := [18][13]Rect {
	0 = {
		 0 = {68, 44, 16, 16},
		 1 = {87, 44, 16, 16},
		 2 = {106, 44, 16, 16},
		 3 = {308, 44, 16, 16},
		 4 = {327, 44, 16, 16},
		 5 = {346, 44, 16, 16},
		 6 = {365, 44, 16, 16},
		 7 = {384, 44, 16, 16},
		 8 = {403, 44, 16, 16},
		 9 = {422, 44, 16, 16},
		 10 = {20, 45, 16, 16},
		 11 = {39, 45, 16, 16},
		 12 = {1, 49, 16, 16},
	},
	1 = {
		 0 = {125, 62, 16, 16},
		 1 = {144, 62, 16, 16},
		 2 = {163, 62, 16, 16},
		 3 = {182, 62, 16, 16},
		 4 = {201, 62, 16, 16},
		 5 = {220, 62, 16, 16},
		 6 = {239, 62, 16, 16},
		 7 = {258, 62, 16, 16},
		 8 = {277, 62, 16, 16},
		 9 = {441, 62, 16, 16},
		 10 = {460, 62, 16, 16},
		 11 = {479, 62, 16, 16},
		 12 = {58, 63, 16, 16},
	},
	2 = {
		 0 = {77, 63, 16, 16},
		 1 = {96, 63, 16, 16},
		 2 = {296, 63, 16, 16},
		 3 = {315, 63, 16, 16},
		 4 = {334, 63, 16, 16},
		 5 = {353, 63, 16, 16},
		 6 = {372, 63, 16, 16},
		 7 = {391, 63, 16, 16},
		 8 = {410, 63, 16, 16},
		 9 = {20, 64, 16, 16},
		 10 = {39, 64, 16, 16},
		 11 = {1, 68, 16, 16},
		 12 = {115, 81, 16, 16},
	},
	3 = {
		 0 = {134, 81, 16, 16},
		 1 = {153, 81, 16, 16},
		 2 = {172, 81, 16, 16},
		 3 = {191, 81, 16, 16},
		 4 = {210, 81, 16, 16},
		 5 = {229, 81, 16, 16},
		 6 = {248, 81, 16, 16},
		 7 = {267, 81, 16, 16},
		 8 = {429, 81, 16, 16},
		 9 = {448, 81, 16, 16},
		 10 = {467, 81, 16, 16},
		 11 = {486, 81, 16, 16},
		 12 = {58, 82, 16, 16},
	},
	4 = {
		 0 = {77, 82, 16, 16},
		 1 = {96, 82, 16, 16},
		 2 = {286, 82, 16, 16},
		 3 = {305, 82, 16, 16},
		 4 = {324, 82, 16, 16},
		 5 = {343, 82, 16, 16},
		 6 = {362, 82, 16, 16},
		 7 = {381, 82, 16, 16},
		 8 = {400, 82, 16, 16},
		 9 = {20, 83, 16, 16},
		 10 = {39, 83, 16, 16},
		 11 = {1, 87, 16, 16},
		 12 = {115, 100, 16, 16},
	},
	5 = {
		 0 = {134, 100, 16, 16},
		 1 = {153, 100, 16, 16},
		 2 = {172, 100, 16, 16},
		 3 = {191, 100, 16, 16},
		 4 = {210, 100, 16, 16},
		 5 = {229, 100, 16, 16},
		 6 = {248, 100, 16, 16},
		 7 = {267, 100, 16, 16},
		 8 = {419, 100, 16, 16},
		 9 = {438, 100, 16, 16},
		 10 = {457, 100, 16, 16},
		 11 = {476, 100, 16, 16},
		 12 = {58, 101, 16, 16},
	},
	6 = {
		 0 = {77, 101, 16, 16},
		 1 = {96, 101, 16, 16},
		 2 = {286, 101, 16, 16},
		 3 = {305, 101, 16, 16},
		 4 = {324, 101, 16, 16},
		 5 = {343, 101, 16, 16},
		 6 = {362, 101, 16, 16},
		 7 = {381, 101, 16, 16},
		 8 = {400, 101, 16, 16},
		 9 = {20, 102, 16, 16},
		 10 = {39, 102, 16, 16},
		 11 = {1, 106, 16, 16},
		 12 = {115, 119, 16, 16},
	},
	7 = {
		 0 = {134, 119, 16, 16},
		 1 = {153, 119, 16, 16},
		 2 = {172, 119, 16, 16},
		 3 = {191, 119, 16, 16},
		 4 = {210, 119, 16, 16},
		 5 = {229, 119, 16, 16},
		 6 = {248, 119, 16, 16},
		 7 = {267, 119, 16, 16},
		 8 = {419, 119, 16, 16},
		 9 = {438, 119, 16, 16},
		 10 = {457, 119, 16, 16},
		 11 = {476, 119, 16, 16},
		 12 = {58, 120, 16, 16},
	},
	8 = {
		 0 = {77, 120, 16, 16},
		 1 = {96, 120, 16, 16},
		 2 = {286, 120, 16, 16},
		 3 = {305, 120, 16, 16},
		 4 = {324, 120, 16, 16},
		 5 = {343, 120, 16, 16},
		 6 = {362, 120, 16, 16},
		 7 = {381, 120, 16, 16},
		 8 = {400, 120, 16, 16},
		 9 = {20, 121, 16, 16},
		 10 = {39, 121, 16, 16},
		 11 = {1, 125, 16, 16},
		 12 = {115, 138, 16, 16},
	},
	9 = {
		 0 = {134, 138, 16, 16},
		 1 = {153, 138, 16, 16},
		 2 = {172, 138, 16, 16},
		 3 = {191, 138, 16, 16},
		 4 = {210, 138, 16, 16},
		 5 = {229, 138, 16, 16},
		 6 = {248, 138, 16, 16},
		 7 = {267, 138, 16, 16},
		 8 = {419, 138, 16, 16},
		 9 = {438, 138, 16, 16},
		 10 = {457, 138, 16, 16},
		 11 = {476, 138, 16, 16},
		 12 = {58, 139, 16, 16},
	},
	10 = {
		 0 = {77, 139, 16, 16},
		 1 = {96, 139, 16, 16},
		 2 = {286, 139, 16, 16},
		 3 = {305, 139, 16, 16},
		 4 = {324, 139, 16, 16},
		 5 = {343, 139, 16, 16},
		 6 = {362, 139, 16, 16},
		 7 = {381, 139, 16, 16},
		 8 = {400, 139, 16, 16},
		 9 = {20, 140, 16, 16},
		 10 = {39, 140, 16, 16},
		 11 = {1, 144, 16, 16},
		 12 = {115, 157, 16, 16},
	},
	11 = {
		 0 = {134, 157, 16, 16},
		 1 = {153, 157, 16, 16},
		 2 = {172, 157, 16, 16},
		 3 = {191, 157, 16, 16},
		 4 = {210, 157, 16, 16},
		 5 = {229, 157, 16, 16},
		 6 = {248, 157, 16, 16},
		 7 = {267, 157, 16, 16},
		 8 = {419, 157, 16, 16},
		 9 = {438, 157, 16, 16},
		 10 = {457, 157, 16, 16},
		 11 = {476, 157, 16, 16},
		 12 = {58, 158, 16, 16},
	},
	12 = {
		 0 = {77, 158, 16, 16},
		 1 = {96, 158, 16, 16},
		 2 = {137, 24, 16, 16},
		 3 = {286, 158, 16, 16},
		 4 = {305, 158, 16, 16},
		 5 = {324, 158, 16, 16},
		 6 = {343, 158, 16, 16},
		 7 = {362, 158, 16, 16},
		 8 = {381, 158, 16, 16},
		 9 = {400, 158, 16, 16},
		 10 = {20, 159, 16, 16},
		 11 = {39, 159, 16, 16},
		 12 = {1, 163, 16, 16},
	},
	13 = {
		 0 = {115, 176, 16, 16},
		 1 = {134, 176, 16, 16},
		 2 = {153, 176, 16, 16},
		 3 = {172, 176, 16, 16},
		 4 = {191, 176, 16, 16},
		 5 = {210, 176, 16, 16},
		 6 = {229, 176, 16, 16},
		 7 = {248, 176, 16, 16},
		 8 = {267, 176, 16, 16},
		 9 = {419, 176, 16, 16},
		 10 = {438, 176, 16, 16},
		 11 = {457, 176, 16, 16},
		 12 = {476, 176, 16, 16},
	},
	14 = {
		 0 = {58, 177, 16, 16},
		 1 = {77, 177, 16, 16},
		 2 = {96, 177, 16, 16},
		 3 = {286, 177, 16, 16},
		 4 = {305, 177, 16, 16},
		 5 = {324, 177, 16, 16},
		 6 = {343, 177, 16, 16},
		 7 = {362, 177, 16, 16},
		 8 = {381, 177, 16, 16},
		 9 = {400, 177, 16, 16},
		 10 = {20, 178, 16, 16},
		 11 = {39, 178, 16, 16},
		 12 = {1, 182, 16, 16},
	},
	15 = {
		 0 = {115, 195, 16, 16},
		 1 = {134, 195, 16, 16},
		 2 = {153, 195, 16, 16},
		 3 = {172, 195, 16, 16},
		 4 = {191, 195, 16, 16},
		 5 = {210, 195, 16, 16},
		 6 = {229, 195, 16, 16},
		 7 = {248, 195, 16, 16},
		 8 = {267, 195, 16, 16},
		 9 = {419, 195, 16, 16},
		 10 = {438, 195, 16, 16},
		 11 = {457, 195, 16, 16},
		 12 = {476, 195, 16, 16},
	},
	16 = {
		 0 = {58, 196, 16, 16},
		 1 = {77, 196, 16, 16},
		 2 = {156, 24, 16, 16},
		 3 = {175, 24, 16, 16},
		 4 = {194, 24, 16, 16},
		 5 = {213, 24, 16, 16},
		 6 = {232, 24, 16, 16},
		 7 = {251, 24, 16, 16},
		 8 = {270, 24, 16, 16},
		 9 = {289, 24, 16, 16},
		 10 = {80, 25, 16, 16},
		 11 = {30, 26, 16, 16},
		 12 = {49, 26, 16, 16},
	},
	17 = {
		 0 = {1, 30, 16, 16},
		 1 = {137, 43, 16, 16},
		 2 = {156, 43, 16, 16},
		 3 = {175, 43, 16, 16},
		 4 = {194, 43, 16, 16},
		 5 = {213, 43, 16, 16},
		 6 = {232, 43, 16, 16},
		 7 = {251, 43, 16, 16},
		 8 = {270, 43, 16, 16},
		 9 = {289, 43, 16, 16},
		 10 = {442, 43, 16, 16},
		 11 = {461, 43, 16, 16},
		 12 = {480, 43, 16, 16},
	},
}

// The rect inside the atlas where each tile has ended up.
// Index using tileset_normal[x][y].
tileset_normal := [18][13]Rect {
}

Atlas_Glyph :: struct {
	rect: Rect,
	value: rune,
	offset_x: int,
	offset_y: int,
	advance_x: int,
}

atlas_glyphs: []Atlas_Glyph = {
	{ rect = {442, 23, 11, 18}, value = 'A', offset_x = 0, offset_y = 3, advance_x = 11},
	{ rect = {180, 1, 13, 21}, value = 'B', offset_x = 0, offset_y = 1, advance_x = 14},
	{ rect = {116, 24, 13, 18}, value = 'C', offset_x = 0, offset_y = 3, advance_x = 12},
	{ rect = {99, 24, 15, 18}, value = 'D', offset_x = 0, offset_y = 3, advance_x = 14},
	{ rect = {290, 1, 11, 21}, value = 'E', offset_x = 1, offset_y = 1, advance_x = 12},
	{ rect = {423, 23, 11, 19}, value = 'F', offset_x = 1, offset_y = 2, advance_x = 11},
	{ rect = {195, 1, 12, 21}, value = 'G', offset_x = 1, offset_y = 2, advance_x = 13},
	{ rect = {403, 1, 11, 20}, value = 'H', offset_x = 1, offset_y = 2, advance_x = 12},
	{ rect = {436, 23, 4, 19}, value = 'I', offset_x = 1, offset_y = 2, advance_x = 5},
	{ rect = {303, 1, 9, 21}, value = 'J', offset_x = 0, offset_y = 1, advance_x = 10},
	{ rect = {358, 1, 13, 20}, value = 'K', offset_x = 1, offset_y = 2, advance_x = 13},
	{ rect = {264, 1, 11, 21}, value = 'L', offset_x = 1, offset_y = 2, advance_x = 11},
	{ rect = {99, 1, 16, 21}, value = 'M', offset_x = 1, offset_y = 1, advance_x = 17},
	{ rect = {117, 1, 15, 21}, value = 'N', offset_x = 1, offset_y = 1, advance_x = 16},
	{ rect = {455, 22, 15, 19}, value = 'O', offset_x = 0, offset_y = 2, advance_x = 16},
	{ rect = {388, 1, 13, 20}, value = 'P', offset_x = 0, offset_y = 2, advance_x = 13},
	{ rect = {80, 1, 17, 22}, value = 'Q', offset_x = 0, offset_y = 2, advance_x = 17},
	{ rect = {342, 1, 14, 20}, value = 'R', offset_x = 1, offset_y = 2, advance_x = 14},
	{ rect = {165, 1, 13, 21}, value = 'S', offset_x = 0, offset_y = 1, advance_x = 14},
	{ rect = {472, 22, 14, 19}, value = 'T', offset_x = 0, offset_y = 2, advance_x = 14},
	{ rect = {134, 1, 14, 21}, value = 'U', offset_x = 1, offset_y = 1, advance_x = 16},
	{ rect = {492, 1, 15, 19}, value = 'V', offset_x = 0, offset_y = 2, advance_x = 15},
	{ rect = {455, 1, 18, 19}, value = 'W', offset_x = 1, offset_y = 3, advance_x = 19},
	{ rect = {475, 1, 15, 19}, value = 'X', offset_x = 0, offset_y = 2, advance_x = 15},
	{ rect = {325, 1, 15, 20}, value = 'Y', offset_x = 0, offset_y = 2, advance_x = 15},
	{ rect = {495, 100, 12, 17}, value = 'Z', offset_x = 1, offset_y = 3, advance_x = 14},
	{ rect = {20, 197, 11, 11}, value = 'a', offset_x = 1, offset_y = 11, advance_x = 12},
	{ rect = {251, 1, 11, 21}, value = 'b', offset_x = 1, offset_y = 1, advance_x = 12},
	{ rect = {299, 196, 10, 13}, value = 'c', offset_x = 1, offset_y = 10, advance_x = 11},
	{ rect = {495, 138, 12, 15}, value = 'd', offset_x = 1, offset_y = 7, advance_x = 14},
	{ rect = {495, 172, 10, 15}, value = 'e', offset_x = 1, offset_y = 8, advance_x = 12},
	{ rect = {429, 1, 9, 20}, value = 'f', offset_x = 1, offset_y = 2, advance_x = 8},
	{ rect = {416, 1, 11, 20}, value = 'g', offset_x = 1, offset_y = 11, advance_x = 12},
	{ rect = {373, 1, 13, 20}, value = 'h', offset_x = 1, offset_y = 2, advance_x = 14},
	{ rect = {131, 24, 4, 18}, value = 'i', offset_x = 1, offset_y = 3, advance_x = 5},
	{ rect = {1, 1, 9, 27}, value = 'j', offset_x = -3, offset_y = 5, advance_x = 6},
	{ rect = {354, 23, 12, 19}, value = 'k', offset_x = 0, offset_y = 3, advance_x = 12},
	{ rect = {504, 22, 4, 19}, value = 'l', offset_x = 1, offset_y = 2, advance_x = 5},
	{ rect = {350, 196, 18, 11}, value = 'm', offset_x = 1, offset_y = 11, advance_x = 20},
	{ rect = {286, 196, 11, 13}, value = 'n', offset_x = 0, offset_y = 9, advance_x = 12},
	{ rect = {33, 197, 11, 11}, value = 'o', offset_x = 1, offset_y = 10, advance_x = 12},
	{ rect = {325, 23, 13, 19}, value = 'p', offset_x = 0, offset_y = 10, advance_x = 14},
	{ rect = {209, 1, 12, 21}, value = 'q', offset_x = 1, offset_y = 10, advance_x = 13},
	{ rect = {311, 196, 9, 13}, value = 'r', offset_x = 1, offset_y = 9, advance_x = 10},
	{ rect = {502, 189, 7, 14}, value = 's', offset_x = 1, offset_y = 9, advance_x = 9},
	{ rect = {495, 119, 9, 17}, value = 't', offset_x = 0, offset_y = 5, advance_x = 10},
	{ rect = {96, 196, 13, 13}, value = 'u', offset_x = 1, offset_y = 10, advance_x = 14},
	{ rect = {337, 196, 11, 12}, value = 'v', offset_x = 1, offset_y = 10, advance_x = 12},
	{ rect = {370, 196, 14, 11}, value = 'w', offset_x = 1, offset_y = 11, advance_x = 16},
	{ rect = {401, 196, 11, 11}, value = 'x', offset_x = 1, offset_y = 12, advance_x = 12},
	{ rect = {495, 155, 10, 15}, value = 'y', offset_x = 1, offset_y = 12, advance_x = 12},
	{ rect = {322, 196, 13, 12}, value = 'z', offset_x = 1, offset_y = 10, advance_x = 13},
	{ rect = {440, 1, 7, 20}, value = '1', offset_x = 0, offset_y = 2, advance_x = 8},
	{ rect = {396, 23, 12, 19}, value = '2', offset_x = 0, offset_y = 2, advance_x = 12},
	{ rect = {382, 23, 12, 19}, value = '3', offset_x = 0, offset_y = 2, advance_x = 12},
	{ rect = {340, 23, 12, 19}, value = '4', offset_x = 1, offset_y = 2, advance_x = 12},
	{ rect = {277, 1, 11, 21}, value = '5', offset_x = 1, offset_y = 1, advance_x = 12},
	{ rect = {237, 1, 12, 21}, value = '6', offset_x = 1, offset_y = 1, advance_x = 13},
	{ rect = {223, 1, 12, 21}, value = '7', offset_x = 0, offset_y = 1, advance_x = 11},
	{ rect = {410, 23, 11, 19}, value = '8', offset_x = 1, offset_y = 1, advance_x = 11},
	{ rect = {150, 1, 13, 21}, value = '9', offset_x = 0, offset_y = 1, advance_x = 13},
	{ rect = {368, 23, 12, 19}, value = '0', offset_x = 1, offset_y = 2, advance_x = 14},
	{ rect = {314, 1, 9, 21}, value = '?', offset_x = 1, offset_y = 1, advance_x = 10},
	{ rect = {449, 1, 4, 20}, value = '!', offset_x = 1, offset_y = 2, advance_x = 5},
	{ rect = {488, 22, 14, 19}, value = '&', offset_x = 1, offset_y = 3, advance_x = 15},
	{ rect = {12, 201, 5, 5}, value = '.', offset_x = 1, offset_y = 17, advance_x = 7},
	{ rect = {46, 197, 5, 10}, value = ',', offset_x = 1, offset_y = 15, advance_x = 7},
	{ rect = {495, 206, 11, 4}, value = '_', offset_x = 1, offset_y = 20, advance_x = 12},
	{ rect = {495, 189, 5, 15}, value = ':', offset_x = 1, offset_y = 7, advance_x = 7},
	{ rect = {12, 1, 7, 25}, value = '[', offset_x = 1, offset_y = 0, advance_x = 7},
	{ rect = {21, 1, 7, 25}, value = ']', offset_x = 0, offset_y = 0, advance_x = 8},
	{ rect = {350, 209, 11, 3}, value = '-', offset_x = 1, offset_y = 14, advance_x = 12},
	{ rect = {386, 196, 13, 11}, value = '+', offset_x = 1, offset_y = 9, advance_x = 14},
}
