// This file is generated by running the atlas_builder.
package shooter

/*
Note: This file assumes the existence of a type Rect that defines a rectangle in the same package, it can defined as:

	Rect :: rl.Rectangle

or if you don't use raylib:

	Rect :: struct {
		x, y, width, height: f32,
	}

or if you want to use integers (or any other numeric type):

	Rect :: struct {
		x, y, width, height: int,
	}

Just make sure you have something along those lines the same package as this file.
*/

TEXTURE_ATLAS_FILENAME :: "data/atlas.png"
ATLAS_FONT_SIZE :: 32
LETTERS_IN_FONT :: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890?!&.,_:[]-+"

// A generated square in the atlas you can use with rl.SetShapesTexture to make
// raylib shapes such as rl.DrawRectangleRec() use the atlas.
SHAPES_TEXTURE_RECT :: Rect {0, 29, 10, 10}

Texture_Name :: enum {
	None,
	Player0,
	Player1,
}

Atlas_Texture :: struct {
	rect: Rect,
	// These offsets tell you how much space there is between the rect and the edge of the original document.
	// The atlas is tightly packed, so empty pixels are removed. This can be especially apparent in animations where
	// frames can have different offsets due to different amount of empty pixels around the frames.
	// In many cases you need to add {offset_left, offset_top} to your position. But if you are
	// flipping a texture, then you might need offset_bottom or offset_right.
	offset_top: f32,
	offset_right: f32,
	offset_bottom: f32,
	offset_left: f32,
	document_size: [2]f32,
	duration: f32,
}

atlas_textures: [Texture_Name]Atlas_Texture = {
	.None = {},
	.Player0 = { rect = {29, 0, 24, 24}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {24, 24}, duration = 0.100},
	.Player1 = { rect = {54, 0, 24, 24}, offset_top = 0, offset_right = 0, offset_bottom = 0, offset_left = 0, document_size = {24, 24}, duration = 0.100},
}

Animation_Name :: enum {
	None,
	Player_Walk,
}

Tag_Loop_Dir :: enum {
	Forward,
	Reverse,
	Ping_Pong,
	Ping_Pong_Reverse,
}

// Any aseprite file with frames will create new animations. Also, any tags
// within the aseprite file will make that that into a separate animation.
Atlas_Animation :: struct {
	first_frame: Texture_Name,
	last_frame: Texture_Name,
	document_size: [2]f32,
	loop_direction: Tag_Loop_Dir,
	repeat: u16,
}

atlas_animations := [Animation_Name]Atlas_Animation {
	.None = {},
	.Player_Walk = { first_frame = .Player0, last_frame = .Player1, loop_direction = .Forward, repeat = 0, document_size = {0, 0} },
}

Atlas_Glyph :: struct {
	rect: Rect,
	value: rune,
	offset_x: int,
	offset_y: int,
	advance_x: int,
}

atlas_glyphs: []Atlas_Glyph = {
	{ rect = {442, 23, 11, 18}, value = 'A', offset_x = 0, offset_y = 3, advance_x = 11},
	{ rect = {150, 1, 13, 21}, value = 'B', offset_x = 0, offset_y = 1, advance_x = 14},
	{ rect = {116, 24, 13, 18}, value = 'C', offset_x = 0, offset_y = 3, advance_x = 12},
	{ rect = {99, 24, 15, 18}, value = 'D', offset_x = 0, offset_y = 3, advance_x = 14},
	{ rect = {290, 1, 11, 21}, value = 'E', offset_x = 1, offset_y = 1, advance_x = 12},
	{ rect = {410, 23, 11, 19}, value = 'F', offset_x = 1, offset_y = 2, advance_x = 11},
	{ rect = {209, 1, 12, 21}, value = 'G', offset_x = 1, offset_y = 2, advance_x = 13},
	{ rect = {416, 1, 11, 20}, value = 'H', offset_x = 1, offset_y = 2, advance_x = 12},
	{ rect = {436, 23, 4, 19}, value = 'I', offset_x = 1, offset_y = 2, advance_x = 5},
	{ rect = {314, 1, 9, 21}, value = 'J', offset_x = 0, offset_y = 1, advance_x = 10},
	{ rect = {358, 1, 13, 20}, value = 'K', offset_x = 1, offset_y = 2, advance_x = 13},
	{ rect = {251, 1, 11, 21}, value = 'L', offset_x = 1, offset_y = 2, advance_x = 11},
	{ rect = {99, 1, 16, 21}, value = 'M', offset_x = 1, offset_y = 1, advance_x = 17},
	{ rect = {117, 1, 15, 21}, value = 'N', offset_x = 1, offset_y = 1, advance_x = 16},
	{ rect = {475, 1, 15, 19}, value = 'O', offset_x = 0, offset_y = 2, advance_x = 16},
	{ rect = {388, 1, 13, 20}, value = 'P', offset_x = 0, offset_y = 2, advance_x = 13},
	{ rect = {80, 1, 17, 22}, value = 'Q', offset_x = 0, offset_y = 2, advance_x = 17},
	{ rect = {342, 1, 14, 20}, value = 'R', offset_x = 1, offset_y = 2, advance_x = 14},
	{ rect = {180, 1, 13, 21}, value = 'S', offset_x = 0, offset_y = 1, advance_x = 14},
	{ rect = {488, 22, 14, 19}, value = 'T', offset_x = 0, offset_y = 2, advance_x = 14},
	{ rect = {134, 1, 14, 21}, value = 'U', offset_x = 1, offset_y = 1, advance_x = 16},
	{ rect = {492, 1, 15, 19}, value = 'V', offset_x = 0, offset_y = 2, advance_x = 15},
	{ rect = {455, 1, 18, 19}, value = 'W', offset_x = 1, offset_y = 3, advance_x = 19},
	{ rect = {455, 22, 15, 19}, value = 'X', offset_x = 0, offset_y = 2, advance_x = 15},
	{ rect = {325, 1, 15, 20}, value = 'Y', offset_x = 0, offset_y = 2, advance_x = 15},
	{ rect = {137, 24, 12, 17}, value = 'Z', offset_x = 1, offset_y = 3, advance_x = 14},
	{ rect = {45, 26, 11, 11}, value = 'a', offset_x = 1, offset_y = 11, advance_x = 12},
	{ rect = {277, 1, 11, 21}, value = 'b', offset_x = 1, offset_y = 1, advance_x = 12},
	{ rect = {244, 24, 10, 13}, value = 'c', offset_x = 1, offset_y = 10, advance_x = 11},
	{ rect = {162, 24, 12, 15}, value = 'd', offset_x = 1, offset_y = 7, advance_x = 14},
	{ rect = {188, 24, 10, 15}, value = 'e', offset_x = 1, offset_y = 8, advance_x = 12},
	{ rect = {429, 1, 9, 20}, value = 'f', offset_x = 1, offset_y = 2, advance_x = 8},
	{ rect = {403, 1, 11, 20}, value = 'g', offset_x = 1, offset_y = 11, advance_x = 12},
	{ rect = {373, 1, 13, 20}, value = 'h', offset_x = 1, offset_y = 2, advance_x = 14},
	{ rect = {131, 24, 4, 18}, value = 'i', offset_x = 1, offset_y = 3, advance_x = 5},
	{ rect = {1, 1, 9, 27}, value = 'j', offset_x = -3, offset_y = 5, advance_x = 6},
	{ rect = {340, 23, 12, 19}, value = 'k', offset_x = 0, offset_y = 3, advance_x = 12},
	{ rect = {504, 22, 4, 19}, value = 'l', offset_x = 1, offset_y = 2, advance_x = 5},
	{ rect = {295, 24, 18, 11}, value = 'm', offset_x = 1, offset_y = 11, advance_x = 20},
	{ rect = {231, 24, 11, 13}, value = 'n', offset_x = 0, offset_y = 9, advance_x = 12},
	{ rect = {12, 28, 11, 11}, value = 'o', offset_x = 1, offset_y = 10, advance_x = 12},
	{ rect = {325, 23, 13, 19}, value = 'p', offset_x = 0, offset_y = 10, advance_x = 14},
	{ rect = {195, 1, 12, 21}, value = 'q', offset_x = 1, offset_y = 10, advance_x = 13},
	{ rect = {256, 24, 9, 13}, value = 'r', offset_x = 1, offset_y = 9, advance_x = 10},
	{ rect = {207, 24, 7, 14}, value = 's', offset_x = 1, offset_y = 9, advance_x = 9},
	{ rect = {151, 24, 9, 17}, value = 't', offset_x = 0, offset_y = 5, advance_x = 10},
	{ rect = {216, 24, 13, 13}, value = 'u', offset_x = 1, offset_y = 10, advance_x = 14},
	{ rect = {282, 24, 11, 12}, value = 'v', offset_x = 1, offset_y = 10, advance_x = 12},
	{ rect = {80, 25, 14, 11}, value = 'w', offset_x = 1, offset_y = 11, advance_x = 16},
	{ rect = {58, 26, 11, 11}, value = 'x', offset_x = 1, offset_y = 12, advance_x = 12},
	{ rect = {176, 24, 10, 15}, value = 'y', offset_x = 1, offset_y = 12, advance_x = 12},
	{ rect = {267, 24, 13, 12}, value = 'z', offset_x = 1, offset_y = 10, advance_x = 13},
	{ rect = {440, 1, 7, 20}, value = '1', offset_x = 0, offset_y = 2, advance_x = 8},
	{ rect = {396, 23, 12, 19}, value = '2', offset_x = 0, offset_y = 2, advance_x = 12},
	{ rect = {354, 23, 12, 19}, value = '3', offset_x = 0, offset_y = 2, advance_x = 12},
	{ rect = {382, 23, 12, 19}, value = '4', offset_x = 1, offset_y = 2, advance_x = 12},
	{ rect = {264, 1, 11, 21}, value = '5', offset_x = 1, offset_y = 1, advance_x = 12},
	{ rect = {223, 1, 12, 21}, value = '6', offset_x = 1, offset_y = 1, advance_x = 13},
	{ rect = {237, 1, 12, 21}, value = '7', offset_x = 0, offset_y = 1, advance_x = 11},
	{ rect = {423, 23, 11, 19}, value = '8', offset_x = 1, offset_y = 1, advance_x = 11},
	{ rect = {165, 1, 13, 21}, value = '9', offset_x = 0, offset_y = 1, advance_x = 13},
	{ rect = {368, 23, 12, 19}, value = '0', offset_x = 1, offset_y = 2, advance_x = 14},
	{ rect = {303, 1, 9, 21}, value = '?', offset_x = 1, offset_y = 1, advance_x = 10},
	{ rect = {449, 1, 4, 20}, value = '!', offset_x = 1, offset_y = 2, advance_x = 5},
	{ rect = {472, 22, 14, 19}, value = '&', offset_x = 1, offset_y = 3, advance_x = 15},
	{ rect = {71, 26, 5, 5}, value = '.', offset_x = 1, offset_y = 17, advance_x = 7},
	{ rect = {315, 24, 5, 10}, value = ',', offset_x = 1, offset_y = 15, advance_x = 7},
	{ rect = {295, 37, 11, 4}, value = '_', offset_x = 1, offset_y = 20, advance_x = 12},
	{ rect = {200, 24, 5, 15}, value = ':', offset_x = 1, offset_y = 7, advance_x = 7},
	{ rect = {21, 1, 7, 25}, value = '[', offset_x = 1, offset_y = 0, advance_x = 7},
	{ rect = {12, 1, 7, 25}, value = ']', offset_x = 0, offset_y = 0, advance_x = 8},
	{ rect = {308, 37, 11, 3}, value = '-', offset_x = 1, offset_y = 14, advance_x = 12},
	{ rect = {30, 26, 13, 11}, value = '+', offset_x = 1, offset_y = 9, advance_x = 14},
}
