package shooter

import "core:fmt"
import "core:os"
import "core:strconv"
import "core:strings"

// The roster's one persistence path: the editor's Presets mode edits the
// live enemy_presets table and Export writes it back out as the Odin literal
// in enemy_presets.odin, the same way vendor/map-builder writes maps.odin.
// There is no loadable format - a build can only ever run a roster it was
// compiled with (ADR-0027) - so this is one-directional, and a tuning session
// shows up as a reviewable diff to a source file.
//
// The generator has to know Enemy_Preset's shape, variant by variant, and
// emit only each variant's authored half (a body's timers and locks are
// runtime, zero on a fresh stamp). enemy_presets_source_test pins the
// checked-in file to this output, so a field added to a variant and not here
// fails the suite rather than the next Export.

ENEMY_PRESETS_SOURCE_PATH :: "enemy_presets.odin"

export_enemy_presets :: proc(path := ENEMY_PRESETS_SOURCE_PATH) -> bool {
	source := enemy_presets_source(enemy_presets, context.temp_allocator)

	file_error := os.write_entire_file(path, transmute([]u8)source)
	if file_error != nil {
		log_error("Couldn't write enemy presets to `{}`: {}", path, file_error)
		return false
	}

	log_info("Wrote the enemy preset table to `{}`", path)
	return true
}

enemy_presets_source :: proc(presets: [Enemy_Kind]Enemy_Preset, allocator := context.allocator) -> string {
	b := strings.builder_make(allocator)

	strings.write_string(&b, "// Generated by the editor's Presets mode (export_enemy_presets). Hand edits\n")
	strings.write_string(&b, "// are fine but keep the shape - enemy_presets_source_test pins this file to\n")
	strings.write_string(&b, "// the generator's output. The roster's design notes live on Enemy_Kind's\n")
	strings.write_string(&b, "// cases in enemy.odin, since a regenerated literal cannot carry comments.\n")
	strings.write_string(&b, "package shooter\n\n")
	strings.write_string(&b, "enemy_presets: [Enemy_Kind]Enemy_Preset = {\n")
	for preset, kind in presets {
		fmt.sbprintf(&b, "\t.%v = {{\n", kind)
		strings.write_string(&b, "\t\tmovement = ")
		write_movement_literal(&b, preset.movement)
		strings.write_string(&b, ",\n\t\tattack = ")
		write_attack_literal(&b, preset.attack)
		strings.write_string(&b, ",\n\t\tmax_health = ")
		write_preset_number(&b, preset.max_health)
		strings.write_string(&b, ",\n\t\tcolor = ")
		write_enemy_color_literal(&b, preset.color)
		fmt.sbprintf(&b, ",\n\t\tgold = %v,\n\t\tboss = %v,\n\t}},\n", preset.gold, preset.boss)
	}
	strings.write_string(&b, "}\n")

	return strings.to_string(b)
}

write_movement_literal :: proc(b: ^strings.Builder, movement: Movement_Style) {
	switch m in movement {
	case Grounded:
		strings.write_string(b, "Grounded{speed = ")
		write_preset_number(b, m.speed)
		strings.write_string(b, "}")
	case Floater:
		strings.write_string(b, "Floater{speed = ")
		write_preset_number(b, m.speed)
		strings.write_string(b, ", wobble_amplitude = ")
		write_preset_number(b, m.wobble_amplitude)
		strings.write_string(b, ", wobble_frequency = ")
		write_preset_number(b, m.wobble_frequency)
		strings.write_string(b, ", pull_strength = ")
		write_preset_number(b, m.pull_strength)
		strings.write_string(b, "}")
	case Swarmer:
		strings.write_string(b, "Swarmer{speed = ")
		write_preset_number(b, m.speed)
		strings.write_string(b, "}")
	case Charger:
		strings.write_string(b, "Charger{speed = ")
		write_preset_number(b, m.speed)
		strings.write_string(b, ", dash_speed = ")
		write_preset_number(b, m.dash_speed)
		strings.write_string(b, ", dash_distance = ")
		write_preset_number(b, m.dash_distance)
		strings.write_string(b, ", tell_seconds = ")
		write_preset_number(b, m.tell_seconds)
		strings.write_string(b, ", recovery_seconds = ")
		write_preset_number(b, m.recovery_seconds)
		strings.write_string(b, ", cooldown_seconds = ")
		write_preset_number(b, m.cooldown_seconds)
		strings.write_string(b, "}")
	case:
		strings.write_string(b, "nil")
	}
}

write_attack_literal :: proc(b: ^strings.Builder, attack: Attack_Style) {
	switch a in attack {
	case Melee:
		strings.write_string(b, "Melee{attack_damage = ")
		write_preset_number(b, a.attack_damage)
		strings.write_string(b, ", attack_range = ")
		write_preset_number(b, a.attack_range)
		strings.write_string(b, ", attack_cooldown = ")
		write_preset_number(b, a.attack_cooldown)
		strings.write_string(b, "}")
	case Ranged:
		strings.write_string(b, "Ranged{min_range = ")
		write_preset_number(b, a.min_range)
		strings.write_string(b, ", max_range = ")
		write_preset_number(b, a.max_range)
		strings.write_string(b, ", attack_damage = ")
		write_preset_number(b, a.attack_damage)
		strings.write_string(b, ", projectile_speed = ")
		write_preset_number(b, a.projectile_speed)
		strings.write_string(b, ", fire_rate = ")
		write_preset_number(b, a.fire_rate)
		strings.write_string(b, ", bullet_lifetime = ")
		write_preset_number(b, a.bullet_lifetime)
		strings.write_string(b, "}")
	case Tell_Area:
		// only the live phases and, inside each, only the live entries: the
		// rest of either fixed array is whatever the editor last left there,
		// and the literal's indexed form leaves them zero on the next build
		// exactly as a hand-written one does
		strings.write_string(b, "Tell_Area{phases = {")
		phase_count := tell_area_phase_count(a)
		for p in 0 ..< phase_count {
			if p > 0 {
				strings.write_string(b, ", ")
			}
			phase := a.phases[p]
			fmt.sbprintf(b, "%v = {{enter_below = ", p)
			write_preset_number(b, phase.enter_below)
			strings.write_string(b, ", rotation = {")
			count := clamp(phase.rotation_count, 0, TELL_AREA_MAX_ROTATION)
			for i in 0 ..< count {
				if i > 0 {
					strings.write_string(b, ", ")
				}
				fmt.sbprintf(b, "%v = ", i)
				write_area_attack_literal(b, phase.rotation[i])
			}
			fmt.sbprintf(b, "}}, rotation_count = %v, cooldown_seconds = ", phase.rotation_count)
			write_preset_number(b, phase.cooldown_seconds)
			strings.write_string(b, "}")
		}
		fmt.sbprintf(b, "}}, phase_count = %v}}", a.phase_count)
	case:
		strings.write_string(b, "nil")
	}
}

write_area_attack_literal :: proc(b: ^strings.Builder, area: Area_Attack) {
	strings.write_string(b, "{radius = ")
	write_preset_number(b, area.radius)
	strings.write_string(b, ", reach = ")
	write_preset_number(b, area.reach)
	strings.write_string(b, ", damage = ")
	write_preset_number(b, area.damage)
	strings.write_string(b, ", tell_seconds = ")
	write_preset_number(b, area.tell_seconds)
	strings.write_string(b, "}")
}

// a family colour keeps its constant's name, so the literal still says which
// family the Kind belongs to - the hue rule in enemy_preset_test holds "by
// construction" only while rows take their colour from those constants. Any
// other colour is written out as a literal: still valid source, just one the
// hue test will have an opinion about.
write_enemy_color_literal :: proc(b: ^strings.Builder, color: Color) {
	for constant in enemy_color_constants {
		if constant.color == color {
			strings.write_string(b, constant.name)
			return
		}
	}
	fmt.sbprintf(b, "Color{{%v, %v, %v, %v}}", color[0], color[1], color[2], color[3])
}

// the shortest decimal that parses back to exactly this f32. fmt's %v gives
// an f32 its 8-significant-digit expansion (0.35 prints as 0.34999999), which
// is correct but not a number anyone would author; a slider stops on
// arbitrary values, and the literal should read like one a person typed while
// still stamping the very value the session was tuned at.
write_preset_number :: proc(b: ^strings.Builder, value: f32) {
	for precision in 0 ..= PRESET_NUMBER_MAX_DECIMALS {
		text := fmt.tprintf("%.*f", precision, value)
		if back, ok := strconv.parse_f32(text); ok && back == value {
			strings.write_string(b, text)
			return
		}
	}
	fmt.sbprintf(b, "%v", value)
}

// past this an f32 has no more digits to give, so the fallback above is only
// reached by a value with no finite decimal form (NaN, inf)
PRESET_NUMBER_MAX_DECIMALS :: 10
