// Generated by the editor's Presets mode (export_enemy_presets). Hand edits
// are fine but keep the shape - enemy_presets_source_test pins this file to
// the generator's output. The roster's design notes live on Enemy_Kind's
// cases in enemy.odin, since a regenerated literal cannot carry comments.
package shooter

enemy_presets: [Enemy_Kind]Enemy_Preset = {
	.Grunt = {
		movement = Grounded{speed = 40},
		attack = Melee{attack_damage = 10, attack_range = 10, attack_cooldown = 1},
		max_health = 50,
		color = ENEMY_GROUNDED_COLOR,
		gold = 30,
	},
	.Spitter = {
		movement = Grounded{speed = 35},
		attack = Ranged{min_range = 60, max_range = 120, attack_damage = 8, projectile_speed = 200, fire_rate = 1, bullet_lifetime = 2},
		max_health = 35,
		color = ENEMY_GROUNDED_PALE_COLOR,
		gold = 20,
	},
	.Wraith = {
		movement = Floater{speed = 45, wobble_amplitude = 80, wobble_frequency = 3, pull_strength = 0.35},
		attack = Melee{attack_damage = 10, attack_range = 12, attack_cooldown = 1},
		max_health = 55,
		color = ENEMY_FLOATER_COLOR,
		gold = 35,
	},
	.Lancer = {
		movement = Charger{speed = 55, dash_speed = 260, dash_distance = 140, tell_seconds = 0.5, recovery_seconds = 0.5, cooldown_seconds = 1.5},
		attack = Melee{attack_damage = 10, attack_range = 14, attack_cooldown = 1},
		max_health = 60,
		color = ENEMY_CHARGER_COLOR,
		gold = 50,
	},
	.Sentry = {
		movement = nil,
		attack = Ranged{min_range = 0, max_range = 200, attack_damage = 8, projectile_speed = 180, fire_rate = 0.8, bullet_lifetime = 2},
		max_health = 70,
		color = ENEMY_INERT_COLOR,
		gold = 35,
	},
	.Breaker = {
		movement = Grounded{speed = 30},
		attack = Tell_Area{rotation = {0 = {radius = 28, reach = 40, damage = 18, tell_seconds = 0.6}}, rotation_count = 1, cooldown_seconds = 1.5},
		max_health = 130,
		color = ENEMY_GROUNDED_COLOR,
		gold = 80,
	},
	.Mite = {
		movement = Swarmer{speed = 65},
		attack = Melee{attack_damage = 10, attack_range = 8, attack_cooldown = 1},
		max_health = 20,
		color = ENEMY_SWARMER_COLOR,
		gold = 3,
	},
	.Gazer = {
		movement = Floater{speed = 25, wobble_amplitude = 80, wobble_frequency = 3, pull_strength = 0.35},
		attack = Ranged{min_range = 60, max_range = 120, attack_damage = 8, projectile_speed = 200, fire_rate = 1, bullet_lifetime = 2},
		max_health = 30,
		color = ENEMY_FLOATER_PALE_COLOR,
		gold = 20,
	},
}
