// Generated by the editor's Presets mode (export_enemy_presets). Hand edits
// are fine but keep the shape - enemy_presets_source_test pins this file to
// the generator's output. The roster's design notes live on Enemy_Kind's
// cases in enemy.odin, since a regenerated literal cannot carry comments.
package shooter

enemy_presets: [Enemy_Kind]Enemy_Preset = {
	.Grunt = {
		movement = Grounded{speed = 40},
		attack = Melee{attack_damage = 10, attack_range = 10, attack_cooldown = 1},
		max_health = 50,
		color = ENEMY_GROUNDED_COLOR,
		gold = 30,
		boss = false,
	},
	.Spitter = {
		movement = Grounded{speed = 35},
		attack = Ranged{min_range = 60, max_range = 120, attack_damage = 8, projectile_speed = 200, fire_rate = 1, bullet_lifetime = 2},
		max_health = 35,
		color = ENEMY_GROUNDED_PALE_COLOR,
		gold = 20,
		boss = false,
	},
	.Wraith = {
		movement = Floater{speed = 45, wobble_amplitude = 80, wobble_frequency = 3, pull_strength = 0.35},
		attack = Melee{attack_damage = 10, attack_range = 12, attack_cooldown = 1},
		max_health = 55,
		color = ENEMY_FLOATER_COLOR,
		gold = 35,
		boss = false,
	},
	.Lancer = {
		movement = Charger{speed = 55, dash_speed = 260, dash_distance = 140, tell_seconds = 0.5, recovery_seconds = 0.5, cooldown_seconds = 1.5},
		attack = Melee{attack_damage = 10, attack_range = 14, attack_cooldown = 1},
		max_health = 60,
		color = ENEMY_CHARGER_COLOR,
		gold = 50,
		boss = false,
	},
	.Sentry = {
		movement = nil,
		attack = Ranged{min_range = 0, max_range = 200, attack_damage = 8, projectile_speed = 180, fire_rate = 0.8, bullet_lifetime = 2},
		max_health = 70,
		color = ENEMY_INERT_COLOR,
		gold = 35,
		boss = false,
	},
	.Breaker = {
		movement = Grounded{speed = 30},
		attack = Tell_Area{phases = {0 = {enter_below = 0, rotation = {0 = {radius = 28, reach = 40, damage = 18, tell_seconds = 0.6}}, rotation_count = 1, cooldown_seconds = 1.5}}, phase_count = 1},
		max_health = 130,
		color = ENEMY_GROUNDED_COLOR,
		gold = 80,
		boss = false,
	},
	.Mite = {
		movement = Swarmer{speed = 65},
		attack = Melee{attack_damage = 10, attack_range = 8, attack_cooldown = 1},
		max_health = 20,
		color = ENEMY_SWARMER_COLOR,
		gold = 3,
		boss = false,
	},
	.Gazer = {
		movement = Floater{speed = 25, wobble_amplitude = 80, wobble_frequency = 3, pull_strength = 0.35},
		attack = Ranged{min_range = 60, max_range = 120, attack_damage = 8, projectile_speed = 200, fire_rate = 1, bullet_lifetime = 2},
		max_health = 30,
		color = ENEMY_FLOATER_PALE_COLOR,
		gold = 20,
		boss = false,
	},
	.Warden = {
		movement = Grounded{speed = 28},
		attack = Tell_Area{phases = {0 = {enter_below = 0, rotation = {0 = {radius = 40, reach = 110, damage = 18, tell_seconds = 0.55}, 1 = {radius = 64, reach = 30, damage = 24, tell_seconds = 0.7}}, rotation_count = 2, cooldown_seconds = 1.5}, 1 = {enter_below = 0.66, rotation = {0 = {radius = 40, reach = 130, damage = 18, tell_seconds = 0.55}, 1 = {radius = 64, reach = 30, damage = 24, tell_seconds = 0.65}, 2 = {radius = 44, reach = 130, damage = 18, tell_seconds = 0.5}}, rotation_count = 3, cooldown_seconds = 1.15}, 2 = {enter_below = 0.33, rotation = {0 = {radius = 44, reach = 150, damage = 20, tell_seconds = 0.5}, 1 = {radius = 72, reach = 30, damage = 28, tell_seconds = 0.6}, 2 = {radius = 44, reach = 150, damage = 20, tell_seconds = 0.45}, 3 = {radius = 72, reach = 30, damage = 28, tell_seconds = 0.6}}, rotation_count = 4, cooldown_seconds = 0.8}}, phase_count = 3},
		max_health = 220,
		color = Color{236, 236, 230, 255},
		gold = 250,
		boss = true,
	},
}
